### ISSUE TITLE
Two ami-local processes fight for zmq port?

### ISSUE THREAD

**Issue by chrisvam** [slac-lcls/ami#46]
I believe two ami-local processes on one node fight for a zmq port.  See below.

------------------------------------------------------------------

psanagpu106:~$ ps -ef | grep ami-local
cpo       1631  1552  0 18:45 pts/20   00:00:00 grep --color=auto ami-local
roibabar 30426 21928  0 17:05 pts/42   00:00:04 /cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/bin/python3.7 /cds/home/opr/rixopr/git/lcls2_032421/install/bin/ami-local -l xqfs.fc
psanagpu106:~$ 

psanagpu106:~$ cd git/lcls2
psanagpu106:lcls2$ source setup_env.sh 
(ps-4.3.0) psanagpu106:lcls2$ ami-local -l rix_width.fc -b 1 -f interval=.3 psana://exp=rixx43518,run=45
No module named 'ndarray'
No module named 'pyfftw'
[ 2021-03-30 18:45:41,969 | ami.worker    | INFO    ] Starting worker # 0, sending to collector at tcp://127.0.0.1:5557 PID: 2651
[ 2021-03-30 18:45:41,973 | ami.collector | INFO    ] Starting collector on node # 0 PID: 2652
Process nodecol-n0:
[ 2021-03-30 18:45:41,981 | ami.collector | INFO    ] Starting collector on node # 0 PID: 2663
[ 2021-03-30 18:45:41,982 | ami.comm      | INFO    ] worker000: Started Prometheus client on port: 9205
Process globalcol:
[ 2021-03-30 18:45:41,992 | ami.manager   | INFO    ] Starting manager, controlling 1 workers on 1 nodes PID: 2669
Process manager:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/cds/home/c/cpo/git/ami/ami/multiproc.py", line 33, in run
    self._target(*self._args, **self._kwargs)
  File "/cds/home/c/cpo/git/ami/ami/multiproc.py", line 33, in run
    self._target(*self._args, **self._kwargs)
  File "/cds/home/c/cpo/git/ami/ami/multiproc.py", line 33, in run
    self._target(*self._args, **self._kwargs)
  File "/cds/home/c/cpo/git/ami/ami/local.py", line 172, in _sys_exit
    sys.exit(func(*args, **kwargs))
  File "/cds/home/c/cpo/git/ami/ami/local.py", line 172, in _sys_exit
    sys.exit(func(*args, **kwargs))
  File "/cds/home/c/cpo/git/ami/ami/local.py", line 172, in _sys_exit
    sys.exit(func(*args, **kwargs))
  File "/cds/home/c/cpo/git/ami/ami/collector.py", line 186, in run_global_collector
    hutch)
  File "/cds/home/c/cpo/git/ami/ami/manager.py", line 666, in run_manager
    hutch) as manager:
  File "/cds/home/c/cpo/git/ami/ami/collector.py", line 171, in run_node_collector
    hutch)
  File "/cds/home/c/cpo/git/ami/ami/collector.py", line 154, in run_collector
    prometheus_dir, hutch) as collector:
  File "/cds/home/c/cpo/git/ami/ami/manager.py", line 49, in __init__
    super().__init__(results_addr, hutch=hutch)
  File "/cds/home/c/cpo/git/ami/ami/collector.py", line 154, in run_collector
    prometheus_dir, hutch) as collector:
  File "/cds/home/c/cpo/git/ami/ami/collector.py", line 23, in __init__
    Collector.__init__(self, collector_addr, ctx=self.ctx, hutch=hutch)
  File "/cds/home/c/cpo/git/ami/ami/comm.py", line 897, in __init__
    self.collector.bind(addr)
  File "/cds/home/c/cpo/git/ami/ami/collector.py", line 23, in __init__
    Collector.__init__(self, collector_addr, ctx=self.ctx, hutch=hutch)
  File "/cds/home/c/cpo/git/ami/ami/comm.py", line 897, in __init__
    self.collector.bind(addr)
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/lib/python3.7/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "/cds/home/c/cpo/git/ami/ami/comm.py", line 897, in __init__
    self.collector.bind(addr)
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/lib/python3.7/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.3.0/lib/python3.7/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
zmq.error.ZMQError: Address already in use
zmq.error.ZMQError: Address already in use

**Comment by chrisvam** [comment]
Dan says that using "--ipc" option to ami-local avoids allocating ports.  Empirically this seems to work.
